apiVersion: v1
kind: ConfigMap
metadata:
  name: monte-carlo-service-config
  namespace: default
data:
  kafka-brokers: "kafka-broker-0:9092,kafka-broker-1:9092,kafka-broker-2:9092"
  ray-serve-url: "http://ray-head-svc:8000"
  core-service-url: "http://core-service"
  redis-host: "redis"
  redis-port: "6379"
