apiVersion: v1
kind: Service
metadata:
  name: monte-carlo-service
  namespace: default
  labels:
    app: monte-carlo-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: monte-carlo-service
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
    - name: metrics
      port: 8082
      targetPort: 3002
      protocol: TCP
